services:
  app:
    image: ${ECR_REGISTRY}/nocableapp:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - nocableapp-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/NoCableApp.db
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
      - SmtpGmail__Password=${GMAIL_SMTP_PASS}

volumes:
  nocableapp-data:
    driver: local
